
char * FUN_100dd9170(int param_1)

{
  if (param_1 < 0xbb9) {
    if (param_1 < 0x7e7) {
      if (param_1 < 0x3e9) {
        if (param_1 == 0) {
          return "DspIllegalCommand";
        }
      }
      else {
        switch(param_1) {
        case 0x3e9:
          return "DspCmdVmStart";
        case 0x3ea:
          return "DspCmdVmStop";
        case 0x3eb:
          return "DspCmdVmSetConfig";
        case 0x3ec:
          return "DspCmdVmGetConfig";
        case 0x3ed:
          return "DspCmdVmGetProblemReport";
        case 0x3ee:
          return "DspCmdVmReset";
        case 0x3ef:
          return "DspCmdVmPause";
        case 0x3f0:
          return "DspCmdVmSuspend";
        case 0x3f1:
          return "DspCmdVmResume";
        case 0x3f2:
          return "DspCmdVmDropSuspendedState";
        case 0x3f3:
          return "DspCmdVmCreateSnapshot";
        case 0x3f4:
          return "DspCmdVmSwitchToSnapshot";
        case 0x3f5:
          return "DspCmdVmGetState";
        case 0x3f6:
          return "DspCmdVmDevConnect";
        case 0x3f7:
          return "DspCmdVmDevGetState";
        case 0x3f8:
          return "DspCmdVmDevDisconnect";
        case 0x3f9:
          return "DspCmdVmDevChangeMedia";
        case 0x3fa:
          return "DspCmdVmTaskRun";
        case 0x3fb:
          return "DspCmdVmTaskGetState";
        case 0x3fc:
          return "DspCmdVmTaskCancel";
        case 0x3fd:
          return "DspCmdVmAnswer";
        case 0x3fe:
          return "DspCmdVmGetLogData";
        case 0x3ff:
          return "DspCmdVmGetMonitorState";
        case 0x400:
          return "DspCmdVmInitiateDevStateNotifications";
        case 0x401:
          return "DspCmdVmInstallTools";
        case 0x402:
          return "DspCmdVmCancelCompact";
        case 0x403:
          return "DspCmdVmGuestLogout";
        case 0x404:
          return "DspCmdVmGuestRunProgram";
        case 0x405:
          return "DspCmdVmGetSuspendedScreen";
        case 0x406:
          return "DspCmdVmMigrateCancel";
        case 0x407:
          return "DspCmdVmRunCompressor";
        case 0x408:
          return "DspCmdVmCancelCompressor";
        case 0x409:
          return "DspCmdVmFinishCompressorInternal";
        case 0x40a:
          return "DspCmdVmDeleteSnapshot";
        case 0x40b:
          return "DspCmdVmGetSnapshotsTree";
        case 0x40c:
          return "DspCmdVmStartEx";
        case 0x40d:
          return "DspCmdVmLoginInGuest";
        case 0x40e:
          return "DspCmdVmUpdateSnapshotData";
        case 0x40f:
          return "DspCmdVmRestartGuest";
        case 0x410:
          return "DspCmdVmInstallUtility";
        case 0x411:
          return "DspCmdVmUpdateToolsSection";
        case 0x412:
          return "DspCmdVmStartVNCServer";
        case 0x413:
          return "DspCmdVmStopVNCServer";
        case 0x414:
          return "DspCmdVmGuestGetNetworkSettings";
        case 0x415:
          return "DspCmdVmAuthWithGuestSecurityDb";
        case 0x416:
          return "DspCmdVmGuestSetUserPasswd";
        case 0x419:
          return "DspCmdVmCompact";
        case 0x41a:
          return "DspCmdVmSuspendCancel";
        case 0x41b:
          return "DspCmdVmChangeLogLevel";
        case 0x41e:
          return "DspCmdVmGetPackedProblemReport";
        case 0x41f:
          return "DspCmdVmChangeSid";
        case 0x420:
          return "DspCmdVmResetUptime";
        case 0x421:
          return "DspCmdVmInternal";
        case 0x422:
          return "DspCmdVmConvertDisks";
        case 0x45b:
          return "DspCmdPrepareForHibernate";
        case 0x45c:
          return "DspCmdAfterHostResume";
        }
      }
    }
    else {
      switch(param_1) {
      case 0x7e7:
        return "DspCmdDirVmCreate";
      case 0x7e8:
        return "DspCmdDirVmDelete";
      case 0x7e9:
        return "DspCmdDirVmClone";
      case 0x7ea:
        return "DspCmdDirVmEditBegin";
      case 0x7eb:
        return "DspCmdDirVmEditCommit";
      case 0x7ec:
        return "DspCmdDirVmMigrate";
      case 0x7ed:
        return "DspCmdDirGetVmList";
      case 0x7ee:
        return "DspCmdDirGetVmConfig";
      case 0x7ef:
        return "DspCmdDirSetVmConfig";
      case 0x7f0:
        return "DspCmdDirCreateImage";
      case 0x7f1:
        return "DspCmdDirRegVm";
      case 0x7f2:
        return "DspCmdDirUnregVm";
      case 0x7f3:
        return "DspCmdDirLockVm";
      case 0x7f4:
        return "DspCmdDirUnlockVm";
      case 0x7f5:
        return "DspCmdDirVerifyVmConfig";
      case 0x7f6:
        return "DspCmdStartSearchConfig";
      case 0x7f7:
        return "DspCmdUserLogin";
      case 0x7f8:
        return "DspCmdUserLoginLocal";
      case 0x7f9:
        return "DspCmdUserLoginLocalStage2";
      case 0x7fa:
        return "DspCmdUserLogoff";
      case 0x7fb:
        return "DspCmdUserAttachEventNotification";
      case 0x7fc:
        return "DspCmdUserGetEvent";
      case 0x7fd:
        return "DspCmdUserGetProfile";
      case 0x7fe:
        return "DspCmdUserProfileBeginEdit";
      case 0x7ff:
        return "DspCmdUserProfileCommit";
      case 0x800:
        return "DspCmdGetHostCommonInfo";
      case 0x801:
        return "DspCmdHostCommonInfoBeginEdit";
      case 0x802:
        return "DspCmdHostCommonInfoCommit";
      case 0x803:
        return "DspCmdUserGetHostHwInfo";
      case 0x804:
        return "DspCmdUserPing";
      case 0x805:
        return "DspCmdUserCancelOperation";
      case 0x806:
        return "DspCmdFsGetDiskList";
      case 0x807:
        return "DspCmdFsGetCurrentDirectory";
      case 0x808:
        return "DspCmdFsGetDirectoryEntries";
      case 0x809:
        return "DspCmdFsGetFileList";
      case 0x80a:
        return "DspCmdFsCreateDirectory";
      case 0x80b:
        return "DspCmdFsRenameEntry";
      case 0x80c:
        return "DspCmdFsRemoveEntry";
      case 0x80d:
        return "DspCmdDirInstallGuestOS";
      case 0x80e:
        return "DspCmdGetVmInfo";
      case 0x80f:
        return "DspCmdSMCGetDispatcherRTInfo";
      case 0x810:
        return "DspCmdSMCGetCommandHistoryByVm";
      case 0x811:
        return "DspCmdSMCGetCommandHistoryByUser";
      case 0x812:
        return "DspCmdSMCShutdownDispatcher";
      case 0x814:
        return "DspCmdSMCRestartDispatcher";
      case 0x815:
        return "DspCmdSMCDisconnectUser";
      case 0x816:
        return "DspCmdSMCDisconnectAllUsers";
      case 0x817:
        return "DspCmdSMCCancelUserCommand";
      case 0x818:
        return "DspCmdSMCShutdownVm";
      case 0x819:
        return "DspCmdSMCRestartVm";
      case 0x81a:
        return "DspCmdSMCShutdownDispatcherInternal";
      case 0x81b:
        return "DspCmdNetPrlNetworkServiceStart";
      case 0x81c:
        return "DspCmdNetPrlNetworkServiceStop";
      case 0x81d:
        return "DspCmdNetPrlNetworkServiceRestart";
      case 0x81e:
        return "DspCmdGetHostStatistics";
      case 0x81f:
        return "DspCmdVmGetStatistics";
      case 0x820:
        return "DspCmdUserUpdateLicense";
      case 0x821:
        return "DspCmdUserGetLicenseInfo";
      case 0x822:
        return "DspCmdVmCreateUnattendedDisk";
      case 0x823:
        return "DspCmdFsCanCreateFile";
      case 0x824:
        return "DspCmdSubscribeToHostStatistics";
      case 0x825:
        return "DspCmdUnsubscribeFromHostStatistics";
      case 0x826:
        return "DspCmdVmSubscribeToGuestStatistics";
      case 0x827:
        return "DspCmdVmUnsubscribeFromGuestStatistics";
      case 0x828:
        return "DspCmdConvertOldHdd";
      case 0x829:
        return "DspCmdUpdateDeviceInfo";
      case 0x82a:
        return "DspCmdAttachToLostTask";
      case 0x82b:
        return "DspCmdGetNetServiceStatus";
      case 0x82c:
        return "DspCmdNetPrlNetworkServiceRestoreDefaults";
      case 0x82d:
        return "DspCmdAddNetAdapter";
      case 0x82e:
        return "DspCmdDeleteNetAdapter";
      case 0x82f:
        return "DspCmdUpdateNetAdapter";
      case 0x830:
        return "DspCmdFileTransferLogin";
      case 0x831:
        return "DspCmdFileTransferLoginResponse";
      case 0x832:
        return "DspCmdFileTransferUpload";
      case 0x833:
        return "DspCmdFileTransferUploadResponse";
      case 0x834:
        return "DspCmdGetVmToolsInfo";
      case 0x835:
        return "DspCmdFsGenerateEntryName";
      case 0x836:
        return "DspCmdLookupParallelsServers";
      case 0x837:
        return "DspCmdVmUpdateSecurity";
      case 0x838:
        return "DspCmdVmSectionValidateConfig";
      case 0x839:
        return "DspCmdUserInfoList";
      case 0x83a:
        return "DspCmdUserInfo";
      case 0x83b:
        return "DspCmdPerfomanceStatistics";
      case 0x83c:
        return "DspCmdAllHostUsers";
      case 0x83d:
        return "DspCmdDirRestoreVm";
      case 0x83e:
        return "DspCmdGetVirtualNetworkList";
      case 0x83f:
        return "DspCmdAddVirtualNetwork";
      case 0x840:
        return "DspCmdUpdateVirtualNetwork";
      case 0x841:
        return "DspCmdDeleteVirtualNetwork";
      case 0x842:
        return "DspCmdConfigureGenericPci";
      case 0x845:
        return "DspCmdGetBackupTree";
      case 0x846:
        return "DspCmdCreateVmBackup";
      case 0x847:
        return "DspCmdRestoreVmBackup";
      case 0x848:
        return "DspCmdRemoveVmBackup";
      case 0x84a:
        return "DspCmdSendProblemReport";
      case 0x84b:
        return "DspCmdVmLock";
      case 0x84c:
        return "DspCmdVmUnlock";
      case 0x84d:
        return "DspCmdSetNonInteractiveSession";
      case 0x850:
        return "DspCmdVmResizeDisk";
      case 0x851:
        return "DspCmdSetSessionConfirmationMode";
      case 0x852:
        return "DspCmdStorageSetValue";
      case 0x853:
        return "DspCmdVmStorageSetValue";
      case 0x854:
        return "DspCmdSendClientStatistics";
      case 0x856:
        return "DspCmdDirReg3rdPartyVm";
      case 0x857:
        return "DspCmdInstallAppliance";
      case 0x858:
        return "DspCmdUpdateOfflineService";
      case 0x859:
        return "DspCmdDeleteOfflineService";
      case 0x85a:
        return "DspCmdGetOfflineServicesList";
      case 0x85b:
        return "DspCmdStartClusterService";
      case 0x85c:
        return "DspCmdStopClusterService";
      case 0x85d:
        return "DspCmdGetVmVirtDevInfo";
      case 0x85e:
        return "DspCmdVmDevHdCheckPassword";
      case 0x85f:
        return "DspCmdVmAuthorise";
      case 0x860:
        return "DspCmdVmChangePassword";
      case 0x861:
        return "DspCmdVmEncrypt";
      case 0x862:
        return "DspCmdVmDecrypt";
      case 0x863:
        return "DspCmdUpdateNetworkClassesConfig";
      case 0x864:
        return "DspCmdGetNetworkClassesConfig";
      case 0x865:
        return "DspCmdUpdateNetworkShapingConfig";
      case 0x866:
        return "DspCmdGetNetworkShapingConfig";
      case 0x867:
        return "DspCmdRestartNetworkShaping";
      case 0x868:
        return "DspCmdRegisterIscsiStorage";
      case 0x869:
        return "DspCmdUnregisterIscsiStorage";
      case 0x86a:
        return "DspCmdExtendIscsiStorage";
      case 0x86b:
        return "DspCmdGetCtTemplateList";
      case 0x86c:
        return "DspCmdGetDefaultVmConfig";
      case 0x86d:
        return "DspCmdRemoveCtTemplate";
      case 0x86e:
        return "DspCmdCopyCtTemplate";
      case 0x870:
        return "DspCmdAddIPPrivateNetwork";
      case 0x871:
        return "DspCmdRemoveIPPrivateNetwork";
      case 0x872:
        return "DspCmdUpdateIPPrivateNetwork";
      case 0x873:
        return "DspCmdGetIPPrivateNetworksList";
      case 0x874:
        return "DspCmdDirCopyImage";
      case 0x875:
        return "DspCmdRefreshPlugins";
      case 0x876:
        return "DspCmdVmMount";
      case 0x877:
        return "DspCmdVmUmount";
      case 0x879:
        return "DspCmdGetPluginsList";
      case 0x87b:
        return "DspCmdDirVmMove";
      case 0x87c:
        return "DspCmdDirVmMigrateClone";
      case 0x87d:
        return "DspCmdGetVmConfigById";
      case 0x87e:
        return "DspCmdDirVmCloneLinked";
      case 0x880:
        return "DspCmdVmSetProtection";
      case 0x881:
        return "DspCmdVmRemoveProtection";
      case 0x882:
        return "DspCmdAddSharedItem";
      case 0x883:
        return "DspCmdUpdateSharedItem";
      case 0x884:
        return "DspCmdRemoveSharedItem";
      case 0x885:
        return "DspCmdGetSharedItemList";
      case 0x886:
        return "DspCmdSwitchFileSharingNotifications";
      case 0x887:
        return "DspCmdRefreshServerInfo";
      case 0x889:
        return "DspCmdBackupBegin";
      case 0x88a:
        return "DspCmdBackupCommit";
      case 0x88b:
        return "DspCmdBackupRollback";
      case 0x88c:
        return "DspCmdGetBackupVmList";
      case 0x88d:
        return "DspCmdVmArchive";
      case 0x88e:
        return "DspCmdVmUnarchive";
      case 0x88f:
        return "DspCmdBackupSendProgress";
      }
    }
  }
  else if (param_1 < 0xfa1) {
    switch(param_1) {
    case 0xbb9:
      return "DspVmRequest";
    case 0xbba:
      return "DspVmResponse";
    case 0xbbb:
      return "DspVmEvent";
    case 0xbbc:
      return "DspVmEventStartVNCServer";
    case 0xbbd:
      return "DspVmEventStopVNCServer";
    case 0xbc0:
      return "DspVmBinaryEvent";
    case 0xbc1:
      return "DspVmBinaryResponse";
    case 0xbc2:
      return "DspVmAnswer";
    case 0xbc3:
      return "DspVmGetHostHwInfo";
    case 0xbc4:
      return "DspVmRetHostHwInfo";
    case 0xbc5:
      return "DspVmSendEchoEvent";
    case 0xbc6:
      return "DspEvtNotifyVm";
    case 0xbcc:
      return "DspEvtHwChanged";
    case 0xbcd:
      return "DspVmAuth";
    case 0xbce:
      return "DspVmGetHardDiskStates";
    case 0xbcf:
      return "DspVmRetHardDiskStates";
    case 0xbd0:
      return "DspVmDevConnect";
    case 0xbd1:
      return "DspVmDevDisconnect";
    case 0xbd2:
      return "DspEvtNetworkPrefChanged";
    case 0xbd3:
      return "DspVmRestoreState";
    case 0xbd4:
      return "DspVmStateInfo";
    }
  }
  else if (param_1 < 4999) {
    switch(param_1) {
    case 0xfa1:
      return "DspCmdCtlGetStatus";
    case 0xfa2:
      return "DspCmdCtlProcessDeferredTaskFinish";
    case 0xfa4:
      return "DspCmdCtlApplyVmConfig";
    case 0xfa5:
      return "DspCmdCtlVmEditWithRename";
    case 0xfa9:
      return "DspCmdCtlVmStandByGuest";
    case 0xfac:
      return "DspCmdCtlLicenseChange";
    case 0xfaf:
      return "DspCmdCtlVmCommitDiskUnfinished";
    case 0xfb0:
      return "DspCmdCtlVmCollectGuestUsage";
    }
  }
  else if (param_1 < 5999) {
    switch(param_1) {
    case 4999:
      return "DspCtlCommandRangeEnd";
    case 0x1389:
      return "DspWsResponse";
    case 0x138a:
      return "DspReplyWsStatus";
    case 0x138b:
      return "DspWsBinaryResponse";
    }
  }
  else if (param_1 == 5999) {
    return "DspWsCommandRangeEnd";
  }
  return "Unknown";
}

