
char * FUN_1003a0420(long param_1,ushort param_2)

{
  if (param_2 < 0xfffd) {
    switch(param_2) {
    case 0:
      return "nop";
    case 1:
      return "mov";
    case 2:
      return "add";
    case 3:
      return "sub";
    case 4:
      return "mad";
    case 5:
      return "mul";
    case 6:
      return "rcp";
    case 7:
      return "rsq";
    case 8:
      return "dp3";
    case 9:
      return "dp4";
    case 10:
      return "min";
    case 0xb:
      return "max";
    case 0xc:
      return "slt";
    case 0xd:
      return "sge";
    case 0xe:
      return "exp";
    case 0xf:
      return "log";
    case 0x10:
      return "lit";
    case 0x11:
      return "dst";
    case 0x12:
      return "lrp";
    case 0x13:
      return "frc";
    case 0x14:
      return "m4x4";
    case 0x15:
      return "m4x3";
    case 0x16:
      return "m3x4";
    case 0x17:
      return "m3x3";
    case 0x18:
      return "m3x2";
    case 0x19:
      return "call";
    case 0x1a:
      return "callnz";
    case 0x1b:
      return "loop";
    case 0x1c:
      return "ret";
    case 0x1d:
      return "endloop";
    case 0x1e:
      return "label";
    case 0x1f:
      return "dcl";
    case 0x20:
      return "pow";
    case 0x21:
      return "crs";
    case 0x22:
      return "sgn";
    case 0x23:
      return "abs";
    case 0x24:
      return "nrm";
    case 0x25:
      return "sincos";
    case 0x26:
      return "rep";
    case 0x27:
      return "endrep";
    case 0x28:
    case 0x29:
      return "if";
    case 0x2a:
      return "else";
    case 0x2b:
      return "endif";
    case 0x2c:
    case 0x2d:
    case 0x60:
      return "break";
    case 0x2e:
      return "mova";
    case 0x2f:
      return "defb";
    case 0x30:
      return "defi";
    case 0x40:
      if (0xffff0103 < *(uint *)(param_1 + 0x18)) {
        return "texcrd";
      }
      return "texcoord";
    case 0x41:
      return "texkill";
    case 0x42:
      if (0xffff0103 < *(uint *)(param_1 + 0x18)) {
        return "texld";
      }
      return "tex";
    case 0x43:
      return "texbem";
    case 0x44:
      return "texbeml";
    case 0x45:
      return "texreg2ar";
    case 0x46:
      return "texreg2gb";
    case 0x47:
      return "texm3x2pad";
    case 0x48:
      return "texm3x2tex";
    case 0x49:
      return "texm3x3pad";
    case 0x4a:
    case 0x4c:
    case 0x4d:
      return "texm3x3tex";
    case 0x4e:
      return "expp";
    case 0x4f:
      return "logp";
    case 0x50:
      return "cnd";
    case 0x51:
      return "def";
    case 0x52:
      return "texreg2rgb";
    case 0x53:
      return "texdp3tex";
    case 0x54:
      return "texm3x2depth";
    case 0x55:
      return "texdp3";
    case 0x56:
      return "texm3x3";
    case 0x57:
      return "texdepth";
    case 0x58:
      return "cmp";
    case 0x59:
      return "bem";
    case 0x5a:
      return "dp2add";
    case 0x5b:
      return "dsx";
    case 0x5c:
      return "dxy";
    case 0x5d:
      return "texldd";
    case 0x5e:
      return "setp";
    case 0x5f:
      return "texldl";
    }
  }
  else if (param_2 == 0xfffd) {
    return "phase";
  }
  return "instr?";
}

