
byte FUN_100757570(undefined8 param_1,undefined8 param_2,long param_3,long param_4)

{
  ulong *puVar1;
  ushort uVar2;
  int iVar3;
  bool bVar4;
  char cVar5;
  byte bVar6;
  int iVar7;
  char *pcVar8;
  void *pvVar9;
  long lVar10;
  long lVar11;
  char *pcVar12;
  ulong uVar13;
  ulong uVar14;
  char *local_b0;
  
  uVar2 = *(ushort *)(param_4 + 0x3c);
  pcVar8 = operator_new__((ulong)uVar2 << 6,(nothrow_t *)PTR_nothrow_100ba21c8);
  if (pcVar8 == (char *)0x0) {
    FUN_1008e3970("","dbgdump",0,"Failed to allocate memory for program headers");
    return 0;
  }
  cVar5 = FUN_100756dc0(param_2,pcVar8,(ulong)uVar2 * (ulong)*(ushort *)(param_4 + 0x3a),
                        *(undefined8 *)(param_4 + 0x28));
  if (cVar5 == '\0') {
    bVar6 = 0;
    FUN_1008e3970("","dbgdump",0,"Couldn\'t read sections");
  }
  else {
    lVar10 = (ulong)*(ushort *)(param_4 + 0x3e) * 0x40;
    uVar14 = *(ulong *)(pcVar8 + lVar10 + 0x20);
    pvVar9 = operator_new__(uVar14,(nothrow_t *)PTR_nothrow_100ba21c8);
    bVar6 = FUN_100756dc0(param_2,pvVar9,uVar14,*(undefined8 *)(pcVar8 + lVar10 + 0x18));
    if (bVar6 == 0) {
      pcVar12 = "Couldn\'t read sections names";
      local_b0 = (char *)0x0;
LAB_100757a53:
      FUN_1008e3970("","dbgdump",0,pcVar12);
    }
    else {
      local_b0 = (char *)0x0;
      if (*(short *)(param_4 + 0x3c) == 0) {
LAB_1007579d5:
        pcVar12 = 
        "No extra VCPU state found, this program need core file generated by prlctl dbgdump and can\'t process generic core files"
        ;
        bVar6 = 0;
        goto LAB_100757a53;
      }
      uVar14 = 0;
      local_b0 = (char *)0x0;
      bVar4 = false;
      do {
        lVar10 = uVar14 * 0x40;
        puVar1 = (ulong *)(pcVar8 + lVar10 + 0x20);
        if (2 < DAT_1011b55f8) {
          pcVar12 = "NULL";
          if (*puVar1 != 0) {
            pcVar12 = (char *)((ulong)*(uint *)(pcVar8 + lVar10) + (long)pvVar9);
          }
          FUN_1008e3970("","dbgdump",3,"%d section %s of type 0x%x size 0x%llx off 0x%llx",
                        uVar14 & 0xffffffff,pcVar12,*(undefined4 *)(pcVar8 + lVar10 + 4),*puVar1,
                        *(undefined8 *)(pcVar8 + lVar10 + 0x18));
        }
        if ((*puVar1 != 0) &&
           (iVar7 = _strncmp((char *)((ulong)*(uint *)(pcVar8 + lVar10) + (long)pvVar9),
                             "Extra VCPU states",0x14), iVar7 == 0)) {
          FUN_1008e3970("","dbgdump",0,"Found extra VCPU state section");
          uVar13 = *puVar1;
          local_b0 = operator_new__(uVar13,(nothrow_t *)PTR_nothrow_100ba21c8);
          bVar6 = FUN_100756dc0(param_2,local_b0,uVar13,*(undefined8 *)(pcVar8 + lVar10 + 0x18));
          if (bVar6 == 0) {
            FUN_1008e3970("","dbgdump",0,"Couldn\'t read extra VCPU state data");
            goto LAB_100757a5c;
          }
          pcVar12 = _strstr(local_b0,">>> VCPU");
          uVar13 = 0;
          for (; iVar7 = (int)uVar13, pcVar12 != (char *)0x0;
              pcVar12 = _strstr(pcVar12 + 1,">>> VCPU")) {
            lVar10 = *(long *)(param_3 + 0x10);
            lVar11 = uVar13 * 0x768;
            _sscanf(pcVar12,
                    ">>> VCPU %u <<<\nRELIABLE: %d\nEFER: %llx\nCR0: %llx\nCR2: %llx\nCR3: %llx\nCR4: %llx\nGDT_BASE: %llx\nGDT_LIMIT: %llx\nLDT_BASE:: %llx\nLDT_LIMIT:: %llx\nIDT_BASE: %llx\nIDT_LIMIT: %llx\nTSS_BASE: %llx\nTSS_LIMIT: %llx\nTR: %hx\nCS_BASE: %llx\nDS_BASE: %llx\nES_BASE: %llx\nSS_BASE: %llx\nFS_BASE: %llx\nGS_BASE: %llx\n"
                    ,lVar10 + 0x5b8 + lVar11,lVar10 + 0x270 + lVar11,lVar10 + 0x228 + lVar11,
                    lVar10 + 0x230 + lVar11,lVar10 + 0x238 + lVar11,lVar10 + 0x90 + lVar11,
                    lVar10 + 0x98 + lVar11,lVar10 + 0x240 + lVar11,lVar10 + 0x248 + lVar11,
                    lVar10 + 0x700 + lVar11,lVar10 + 0x708 + lVar11,lVar10 + 0x250 + lVar11,
                    lVar10 + 600 + lVar11,lVar10 + 0x730 + lVar11,lVar10 + 0x738 + lVar11,
                    lVar10 + 0x711 + lVar11,lVar10 + 0x610 + lVar11,lVar10 + 0x670 + lVar11,
                    lVar10 + 0x5e0 + lVar11,lVar10 + 0x640 + lVar11,lVar10 + 0x6a0 + lVar11,
                    lVar10 + 0x6d0 + lVar11);
            uVar13 = (ulong)(iVar7 + 1);
          }
          iVar3 = *(int *)(param_3 + 0x18);
          if (iVar3 == 0) {
            *(int *)(param_3 + 0x18) = iVar7;
          }
          else if (iVar3 != iVar7) {
            bVar6 = 0;
            FUN_1008e3970("","dbgdump",0,
                          "VCPU count mismatch (%d in PR_STATUS and %d in extra VCPU state)",iVar3,
                          uVar13);
            goto LAB_100757a5c;
          }
          bVar4 = true;
        }
        uVar14 = uVar14 + 1;
      } while ((long)uVar14 < (long)(ulong)*(ushort *)(param_4 + 0x3c));
      if (!bVar4) goto LAB_1007579d5;
    }
LAB_100757a5c:
    operator_delete__(pcVar8);
    if (pvVar9 != (void *)0x0) {
      operator_delete__(pvVar9);
    }
    pcVar8 = local_b0;
    if (local_b0 == (char *)0x0) goto LAB_100757a82;
  }
  operator_delete__(pcVar8);
LAB_100757a82:
  return bVar6 & 1;
}

