
char * FUN_1007e9590(undefined4 param_1)

{
  char *pcVar1;
  
  pcVar1 = "PJOC_UNKNOWN";
  switch(param_1) {
  case 0:
    goto switchD_1007e95b4_caseD_0;
  case 1:
    return "PJOC_JOB_CANCEL";
  case 2:
    return "PJOC_SRV_LOOKUP_PARALLELS_SERVERS";
  case 3:
    return "PJOC_SRV_LOGIN";
  case 4:
    return "PJOC_SRV_LOGIN_LOCAL";
  case 5:
    return "PJOC_SRV_LOGOFF";
  case 6:
    return "PJOC_SRV_GET_SRV_CONFIG";
  case 7:
    return "PJOC_SRV_GET_COMMON_PREFS";
  case 8:
    return "PJOC_SRV_COMMON_PREFS_BEGIN_EDIT";
  case 9:
    return "PJOC_SRV_COMMON_PREFS_COMMIT";
  case 10:
    return "PJOC_SRV_GET_USER_PROFILE";
  case 0xb:
    return "PJOC_SRV_GET_STATISTICS";
  case 0xc:
    return "PJOC_SRV_USER_PROFILE_BEGIN_EDIT";
  case 0xd:
    return "PJOC_SRV_USER_PROFILE_COMMIT";
  case 0xe:
    return "PJOC_SRV_REGISTER_VM";
  case 0xf:
    return "PJOC_SRV_GET_VM_LIST";
  case 0x10:
    return "PJOC_SRV_SUBSCRIBE_TO_HOST_STATISTICS";
  case 0x11:
    return "PJOC_SRV_UNSUBSCRIBE_FROM_HOST_STATISTICS";
  case 0x12:
    return "PJOC_SRV_SHUTDOWN";
  case 0x13:
    return "PJOC_SRV_FS_GET_DISK_LIST";
  case 0x14:
    return "PJOC_SRV_FS_GET_DIR_ENTRIES";
  case 0x15:
    return "PJOC_SRV_FS_CREATE_DIR";
  case 0x16:
    return "PJOC_SRV_FS_REMOVE_ENTRY";
  case 0x17:
    return "PJOC_SRV_FS_CAN_CREATE_FILE";
  case 0x18:
    return "PJOC_SRV_FS_RENAME_ENTRY";
  case 0x19:
    return "PJOC_SRV_FS_GENERATE_ENTRY_NAME";
  case 0x1a:
    return "PJOC_SRV_UPDATE_LICENSE";
  case 0x1b:
    return "PJOC_SRV_GET_LICENSE_INFO";
  case 0x1c:
    return "PJOC_SRV_SEND_ANSWER";
  case 0x1d:
    return "PJOC_SRV_START_SEARCH_VMS";
  case 0x1e:
    return "PJOC_SRV_NET_SERVICE_START";
  case 0x1f:
    return "PJOC_SRV_NET_SERVICE_STOP";
  case 0x20:
    return "PJOC_SRV_NET_SERVICE_RESTART";
  case 0x21:
    return "PJOC_SRV_NET_SERVICE_RESTORE_DEFAULTS";
  case 0x22:
    return "PJOC_SRV_GET_NET_SERVICE_STATUS";
  case 0x23:
    return "PJOC_SRV_ADD_NET_ADAPTER";
  case 0x24:
    return "PJOC_SRV_DELETE_NET_ADAPTER";
  case 0x25:
    return "PJOC_SRV_UPDATE_NET_ADAPTER";
  case 0x26:
    return "PJOC_SRV_GET_PROBLEM_REPORT";
  case 0x27:
    return "PJOC_SRV_ATTACH_TO_LOST_TASK";
  case 0x28:
    return "PJOC_SRV_GET_USER_INFO_LIST";
  case 0x29:
    return "PJOC_SRV_GET_USER_INFO";
  case 0x2a:
    return "PJOC_VM_START";
  case 0x2b:
    return "PJOC_VM_STOP";
  case 0x2c:
    return "PJOC_VM_PAUSE";
  case 0x2d:
    return "PJOC_VM_RESET";
  case 0x2e:
    return "PJOC_VM_SUSPEND";
  default:
    FUN_1008e3970("","Std",0,"Unknown PRL_JOB_OPERATION_CODE value %p");
    pcVar1 = "Unknown";
switchD_1007e95b4_caseD_0:
    return pcVar1;
  case 0x31:
    return "PJOC_VM_DROP_SUSPENDED_STATE";
  case 0x32:
    return "PJOC_VM_CLONE";
  case 0x33:
    return "PJOC_VM_DELETE";
  case 0x34:
    return "PJOC_VM_GET_PROBLEM_REPORT";
  case 0x35:
    return "PJOC_VM_GET_STATE";
  case 0x36:
    return "PJOC_VM_GENERATE_VM_DEV_FILENAME";
  case 0x37:
    return "PJOC_VM_GET_TOOLS_STATE";
  case 0x38:
    return "PJOC_VM_REFRESH_CONFIG";
  case 0x39:
    return "PJOC_VM_GET_STATISTICS";
  case 0x3a:
    return "PJOC_VM_SUBSCRIBE_TO_GUEST_STATISTICS";
  case 0x3b:
    return "PJOC_VM_UNSUBSCRIBE_FROM_GUEST_STATISTICS";
  case 0x3c:
    return "PJOC_VM_REG";
  case 0x3d:
    return "PJOC_VM_UNREG";
  case 0x3e:
    return "PJOC_VM_BEGIN_EDIT";
  case 0x3f:
    return "PJOC_VM_COMMIT";
  case 0x40:
    return "PJOC_VM_CREATE_UNATTENDED_FLOPPY";
  case 0x41:
    return "PJOC_VM_INITIATE_DEV_STATE_NOTIFICATIONS";
  case 0x42:
    return "PJOC_VM_UPDATE_SECURITY";
  case 0x43:
    return "PJOC_VM_VALIDATE_CONFIG";
  case 0x44:
    return "PJOC_VM_DEV_CONNECT";
  case 0x45:
    return "PJOC_VM_DEV_DISCONNECT";
  case 0x46:
    return "PJOC_VM_DEV_CREATE_IMAGE";
  case 0x47:
    return "PJOC_VM_INSTALL_TOOLS";
  case 0x48:
    return "PJOC_VM_SEND_SHUTDOWN_COMMAND";
  case 0x49:
    return "PJOC_VM_SEND_CLIPBOARD_REQUEST";
  case 0x4a:
    return "PJOC_VM_CONNECT_TO_VM";
  case 0x4b:
    return "PJOC_VM_DEV_DISPLAY_CAPTURE_SCREEN";
  case 0x4c:
    return "PJOC_VM_MIGRATE";
  case 0x4d:
    return "PJOC_VM_SEND_DRAGDROP_COMMAND";
  case 0x4e:
    return "PJOC_VM_GUEST_RUN_PROGRAM";
  case 0x4f:
    return "PJOC_VM_GUEST_LOGOUT";
  case 0x50:
    return "PJOC_SRV_SUBSCRIBE_PERFSTATS";
  case 0x51:
    return "PJOC_SRV_UNSUBSCRIBE_PERFSTATS";
  case 0x52:
    return "PJOC_SRV_GET_PERFSTATS";
  case 0x53:
    return "PJOC_VM_SUBSCRIBE_PERFSTATS";
  case 0x54:
    return "PJOC_VM_UNSUBSCRIBE_PERFSTATS";
  case 0x55:
    return "PJOC_VM_GET_PERFSTATS";
  case 0x56:
    return "PJOC_VM_GET_SUSPENDED_SCREEN";
  case 0x57:
    return "PJOC_VM_MIGRATE_CANCEL";
  case 0x58:
    return "PJOC_VM_RUN_COMPRESSOR";
  case 0x59:
    return "PJOC_VM_CANCEL_COMPRESSOR";
  case 0x5a:
    return "PJOC_VM_CREATE_SNAPSHOT";
  case 0x5b:
    return "PJOC_VM_SWITCH_TO_SNAPSHOT";
  case 0x5c:
    return "PJOC_VM_DELETE_SNAPSHOT";
  case 0x5d:
    return "PJOC_VM_GET_SNAPSHOTS_TREE";
  case 0x5e:
    return "PJOC_VM_START_EX";
  case 0x5f:
    return "PJOC_VM_LOGIN_IN_GUEST";
  case 0x60:
    return "PJOC_VM_UPDATE_SNAPSHOT_DATA";
  case 0x61:
    return "PJOC_VM_RESTART";
  case 0x62:
    return "PJOC_VM_INSTALL_UTILITY";
  case 99:
    return "PJOC_VM_UPDATE_TOOLS_SECTION";
  case 100:
    return "PJOC_SRV_GET_ALL_HOST_USERS";
  case 0x65:
    return "PJOC_VM_RESTORE";
  case 0x66:
    return "PJOC_VM_START_VNC_SERVER";
  case 0x67:
    return "PJOC_VM_STOP_VNC_SERVER";
  case 0x68:
    return "PJOC_VM_GUEST_GET_NETWORK_SETTINGS";
  case 0x69:
    return "PJOC_SRV_GET_VIRTUAL_NETWORK_LIST";
  case 0x6a:
    return "PJOC_VM_AUTH_WITH_GUEST_SECURITY_DB";
  case 0x6b:
    return "PJOC_VM_GUEST_SET_USER_PASSWD";
  case 0x6c:
    return "PJOC_SRV_ADD_VIRTUAL_NETWORK";
  case 0x6d:
    return "PJOC_SRV_UPDATE_VIRTUAL_NETWORK";
  case 0x6e:
    return "PJOC_SRV_DELETE_VIRTUAL_NETWORK";
  case 0x6f:
    return "PJOC_SRV_CONFIGURE_GENERIC_PCI";
  case 0x70:
    return "PJOC_SRV_PREPARE_FOR_HIBERNATE";
  case 0x71:
    return "PJOC_SRV_AFTER_HOST_RESUME";
  case 0x72:
    return "PJOC_SRV_GET_BACKUP_TREE";
  case 0x73:
    return "PJOC_SRV_CREATE_VM_BACKUP";
  case 0x74:
    return "PJOC_SRV_RESTORE_VM_BACKUP";
  case 0x75:
    return "PJOC_API_SEND_PROBLEM_REPORT";
  case 0x76:
    return "PJOC_VM_LOCK";
  case 0x77:
    return "PJOC_VM_UNLOCK";
  case 0x78:
    return "PJOC_SRV_SET_NON_INTERACTIVE_SESSION";
  case 0x79:
    return "PJOC_SRV_CREATE_UNATTENDED_CD";
  case 0x7a:
    return "PJOC_SRV_REMOVE_VM_BACKUP";
  case 0x7b:
    return "PJOC_VM_RESIZE_DISK_IMAGE";
  case 0x7c:
    return "PJOC_SRV_SET_SESSION_CONFIRMATION_MODE";
  case 0x7d:
    return "PJOC_SRV_STORE_VALUE_BY_KEY";
  case 0x7e:
    return "PJOC_VM_STORE_VALUE_BY_KEY";
  case 0x7f:
    return "PJOC_VM_COMPACT";
  case 0x80:
    return "PJOC_VM_CANCEL_COMPACT";
  case 0x81:
    return "PJOC_SRV_SEND_CLIENT_STATISTICS";
  case 0x82:
    return "PJOC_VM_GET_PACKED_PROBLEM_REPORT";
  case 0x83:
    return "PJOC_SRV_GET_PACKED_PROBLEM_REPORT";
  case 0x84:
    return "PJOC_API_SEND_PACKED_PROBLEM_REPORT";
  case 0x85:
    return "PJOC_SRV_UPDATE_USB_ASSOC_LIST";
  case 0x86:
    return "PJOC_SRV_REGISTER_3RD_PARTY_VM";
  case 0x87:
    return "PJOC_VM_CHANGE_SID";
  case 0x88:
    return "PJOC_VM_RESET_UPTIME";
  case 0x89:
    return "PJOC_REPORT_ASSEMBLY";
  case 0x8a:
    return "PJOC_SRV_INSTALL_APPLIANCE";
  case 0x8b:
    return "PJOC_SRV_UPDATE_OFFLINE_SERVICE";
  case 0x8c:
    return "PJOC_SRV_DELETE_OFFLINE_SERVICE";
  case 0x8d:
    return "PJOC_SRV_GET_OFFLINE_SERVICES_LIST";
  case 0x8e:
    return "PJOC_SRV_START_CLUSTER_SERVICE";
  case 0x8f:
    return "PJOC_SRV_STOP_CLUSTER_SERVICE";
  case 0x90:
    return "PJOC_VM_CMD_INTERNAL";
  case 0x91:
    return "PJOC_VM_GET_VIRTUAL_DEVICES_INFO";
  case 0x92:
    return "PJOC_VM_CONVERT_DISKS";
  case 0x93:
    return "PJOC_VM_DEV_HD_CHECK_PASSWORD";
  case 0x94:
    return "PJOC_VM_AUTHORISE";
  case 0x95:
    return "PJOC_VM_CHANGE_PASSWORD";
  case 0x96:
    return "PJOC_VM_ENCRYPT";
  case 0x97:
    return "PJOC_VM_DECRYPT";
  case 0x98:
    return "PJOC_SRV_UPDATE_NETWORK_CLASSES_CONFIG";
  case 0x99:
    return "PJOC_SRV_GET_NETWORK_CLASSES_LIST";
  case 0x9a:
    return "PJOC_SRV_UPDATE_NETWORK_SHAPING_CONFIG";
  case 0x9b:
    return "PJOC_SRV_GET_NETWORK_SHAPING_CONFIG";
  case 0x9c:
    return "PJOC_SRV_RESTART_NETWORK_SHAPING";
  case 0x9d:
    return "PJOC_SRV_PROXY_GET_REGISTERED_HOSTS";
  case 0x9e:
    return "PJOC_SRV_REGISTER_ISCSI_STORAGE";
  case 0x9f:
    return "PJOC_SRV_UNREGISTER_ISCSI_STORAGE";
  case 0xa0:
    return "PJOC_SRV_EXTEND_ISCSI_STORAGE";
  case 0xa1:
    return "PJOC_SRV_GET_CT_TEMPLATE_LIST";
  case 0xa2:
    return "PJOC_SRV_CHECK_ALIVE";
  case 0xa3:
    return "PJOC_SRV_GET_DEFAULT_VM_CONFIG";
  case 0xa4:
    return "PJOC_SRV_REMOVE_CT_TEMPLATE";
  case 0xa5:
    return "PJOC_SRV_COPY_CT_TEMPLATE";
  case 0xa6:
    return "PJOC_SRV_ADD_IPPRIVATE_NETWORK";
  case 0xa7:
    return "PJOC_SRV_REMOVE_IPPRIVATE_NETWORK";
  case 0xa8:
    return "PJOC_SRV_UPDATE_IPPRIVATE_NETWORK";
  case 0xa9:
    return "PJOC_SRV_GET_IPPRIVATE_NETWORKS_LIST";
  case 0xaa:
    return "PJOC_VM_DEV_COPY_IMAGE";
  case 0xab:
    return "PJOC_SRV_REFRESH_PLUGINS";
  case 0xac:
    return "PJOC_VM_MOUNT";
  case 0xad:
    return "PJOC_VM_UMOUNT";
  case 0xae:
    return "PJOC_SRV_GET_PLUGINS_LIST";
  case 0xaf:
    return "PJOC_SRV_GET_DISK_FREE_SPACE";
  case 0xb0:
    return "PJOC_DESKTOP_CONTROL_CONNECT";
  case 0xb1:
    return "PJOC_VM_MOVE";
  case 0xb2:
    return "PJOC_SRV_GENERATE_CSR";
  case 0xb3:
    return "PJOC_SRV_SIGN_CERTIFICATION_REQUEST";
  case 0xb4:
    return "PJOC_SRV_GET_VM_CONFIG";
  case 0xb5:
    return "PJOC_PTM_RPC";
  case 0xb6:
    return "PJOC_API_PUT_USER_DATA";
  case 0xb7:
    return "PJOC_API_GET_USER_DATA";
  case 0xb8:
    return "PJOC_API_GET_USER_KEYS";
  case 0xb9:
    return "PJOC_API_REMOVE_USER_DATA";
  case 0xba:
    return "PJOC_API_PUT_ICON";
  case 0xbb:
    return "PJOC_API_VALIDATE_IN_CACHE";
  case 0xbc:
    return "PJOC_SRV_UPDATE_SESSION_INFO";
  case 0xbd:
    return "PJOC_API_SUBSCRIBE_ON_REGISTRATION";
  case 0xbe:
    return "PJOC_SRV_SEND_PROBLEM_REPORT";
  case 0xbf:
    return "PJOC_VM_SEND_PROBLEM_REPORT";
  case 0xc0:
    return "PJOC_VM_SET_PROTECTION";
  case 0xc1:
    return "PJOC_VM_REMOVE_PROTECTION";
  case 0xc2:
    return "PJOC_SRV_ADD_SHARED_ITEM";
  case 0xc3:
    return "PJOC_SRV_UPDATE_SHARED_ITEM";
  case 0xc4:
    return "PJOC_SRV_REMOVE_SHARED_ITEM";
  case 0xc5:
    return "PJOC_SRV_GET_SHARED_ITEM_LIST";
  case 0xc6:
    return "PJOC_SRV_SWITCH_FILE_SHARING_NOTIFICATIONS";
  case 199:
    return "PJOC_SRV_REFRESH_SERVER_INFO";
  case 200:
    return "PJOC_BACKUP_BEGIN";
  case 0xc9:
    return "PJOC_BACKUP_COMMIT";
  case 0xca:
    return "PJOC_BACKUP_ROLLBACK";
  case 0xcb:
    return "PJOC_GET_BACKUP_VIRTUAL_MACHINES";
  case 0xcc:
    return "PJOC_VM_ARCHIVE";
  case 0xcd:
    return "PJOC_VM_UNARCHIVE";
  case 0xce:
    return "PJOC_BACKUP_SEND_PROGRESS";
  }
}

